p8105_hw1_cz2689
================
2022-09-24

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

------------------------------------------------------------------------

# Problem 1

``` r
data("penguins", package = "palmerpenguins")
view(penguins)
skimr::skim(penguins)
```

|                                                  |          |
|:-------------------------------------------------|:---------|
| Name                                             | penguins |
| Number of rows                                   | 344      |
| Number of columns                                | 8        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |          |
| Column type frequency:                           |          |
| factor                                           | 3        |
| numeric                                          | 5        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |          |
| Group variables                                  | None     |

Data summary

**Variable type: factor**

| skim_variable | n_missing | complete_rate | ordered | n_unique | top_counts                  |
|:--------------|----------:|--------------:|:--------|---------:|:----------------------------|
| species       |         0 |          1.00 | FALSE   |        3 | Ade: 152, Gen: 124, Chi: 68 |
| island        |         0 |          1.00 | FALSE   |        3 | Bis: 168, Dre: 124, Tor: 52 |
| sex           |        11 |          0.97 | FALSE   |        2 | mal: 168, fem: 165          |

**Variable type: numeric**

| skim_variable     | n_missing | complete_rate |    mean |     sd |     p0 |     p25 |     p50 |    p75 |   p100 | hist  |
|:------------------|----------:|--------------:|--------:|-------:|-------:|--------:|--------:|-------:|-------:|:------|
| bill_length_mm    |         2 |          0.99 |   43.92 |   5.46 |   32.1 |   39.23 |   44.45 |   48.5 |   59.6 | ▃▇▇▆▁ |
| bill_depth_mm     |         2 |          0.99 |   17.15 |   1.97 |   13.1 |   15.60 |   17.30 |   18.7 |   21.5 | ▅▅▇▇▂ |
| flipper_length_mm |         2 |          0.99 |  200.92 |  14.06 |  172.0 |  190.00 |  197.00 |  213.0 |  231.0 | ▂▇▃▅▂ |
| body_mass_g       |         2 |          0.99 | 4201.75 | 801.95 | 2700.0 | 3550.00 | 4050.00 | 4750.0 | 6300.0 | ▃▇▆▃▂ |
| year              |         0 |          1.00 | 2008.03 |   0.82 | 2007.0 | 2007.00 | 2008.00 | 2009.0 | 2009.0 | ▇▁▇▁▇ |

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

This data set is called penguins, and it includes variables: species,
island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g,
sex, and year. This data set has 344 rows and 8 columns. And the mean
flipper length is 200.92 according to the ‘skimr’ function.

## Plot the penguins data

``` r
ggplot(penguins, aes(x = bill_length_mm , y = flipper_length_mm, colour = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

![](p8105_hw1_cz2689_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

``` r
ggsave("scatter_plot.pdf", height = 6, width = 6)
```

    ## Warning: Removed 2 rows containing missing values (geom_point).

# Problem 2

``` r
p2 = tibble(
  norm = rnorm(10),
  logi = norm > 0,
  char = c("a","b", "c", "d", "e", "f", "g", "h", "i", "j"),
  fact = factor(c("t", "m", "b", "t", "m", "b", "t", "m", "b", "m"))
  )
p2
```

    ## # A tibble: 10 × 4
    ##      norm logi  char  fact 
    ##     <dbl> <lgl> <chr> <fct>
    ##  1 -1.34  FALSE a     t    
    ##  2 -1.54  FALSE b     m    
    ##  3 -1.00  FALSE c     b    
    ##  4  0.329 TRUE  d     t    
    ##  5 -0.613 FALSE e     m    
    ##  6  0.548 TRUE  f     b    
    ##  7  1.81  TRUE  g     t    
    ##  8  0.322 TRUE  h     m    
    ##  9  0.961 TRUE  i     b    
    ## 10 -0.131 FALSE j     m

## Taking the mean of each variable

``` r
a = pull(p2, var = norm)
mean(a)
```

    ## [1] -0.06563381

``` r
b = pull(p2, var = logi)
mean(b)
```

    ## [1] 0.5

``` r
c = pull(p2, var = char)
mean(c)
```

    ## Warning in mean.default(c): argument is not numeric or logical: returning NA

    ## [1] NA

``` r
d = pull(p2, var = fact)
mean(d)
```

    ## Warning in mean.default(d): argument is not numeric or logical: returning NA

    ## [1] NA

As we can see from the output, we can compute mean for only numeric and
logical vector but not for character and factor vector.

## As.numeric function

``` r
e = as.numeric(b)

f = as.numeric(c)

g = as.numeric(d)
```

From the environment, we can see that logical variables were forced into
1 and 0 (standard computer language for true and false), character
variables were forced into N/A (make sense), and factor variables were
forced into integer 1, 2, 3 (some underlying levels). It explain why we
can take the mean of logical variables since this mean represent how
many true and false values there are. We can not take the mean of
character variables since they are N/A. For factor variables, it does
not make sense to take the average. Those level are not what we
assigned. It might not reflect the ture levels we want.
